server:
  port: 9095
spring:
  application:
    name: performance-statistics

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///performance?serverTimezone=Asia/Shanghai
    username: root
    password: 123456